/*
*************************************************************************
DC EMV
Open Source EMV
Copyright (C) 2018  Vicente Da Silva

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see http://www.gnu.org/licenses/
*************************************************************************
*/
using DCEMV.Shared;
using System.Collections.Generic;

namespace DCEMV.EMVProtocol.Kernels
{

    public static class ISOCountryCodesEnum
    {
        public static List<EnumBase> EnumList = new List<EnumBase>();

        public static EMVCountryCode AFG = new EMVCountryCode(4, "AF", "AFG", "Afghanistan");
        public static EMVCountryCode ALA = new EMVCountryCode(248, "AX", "ALA", "Åland Islands");
        public static EMVCountryCode ALB = new EMVCountryCode(8, "AL", "ALB", "Albania");
        public static EMVCountryCode DZA = new EMVCountryCode(12, "DZ", "DZA", "Algeria");
        public static EMVCountryCode ASM = new EMVCountryCode(16, "AS", "ASM", "American Samoa");
        public static EMVCountryCode AND = new EMVCountryCode(20, "AD", "AND", "Andorra");
        public static EMVCountryCode AGO = new EMVCountryCode(24, "AO", "AGO", "Angola");
        public static EMVCountryCode AIA = new EMVCountryCode(660, "AI", "AIA", "Anguilla");
        public static EMVCountryCode ATA = new EMVCountryCode(10, "AQ", "ATA", "Antarctica");
        public static EMVCountryCode ATG = new EMVCountryCode(28, "AG", "ATG", "Antigua and Barbuda");
        public static EMVCountryCode ARG = new EMVCountryCode(32, "AR", "ARG", "Argentina");
        public static EMVCountryCode ARM = new EMVCountryCode(51, "AM", "ARM", "Armenia");
        public static EMVCountryCode ABW = new EMVCountryCode(533, "AW", "ABW", "Aruba");
        public static EMVCountryCode AUS = new EMVCountryCode(36, "AU", "AUS", "Australia");
        public static EMVCountryCode AUT = new EMVCountryCode(40, "AT", "AUT", "Austria");
        public static EMVCountryCode AZE = new EMVCountryCode(31, "AZ", "AZE", "Azerbaijan");
        public static EMVCountryCode BHS = new EMVCountryCode(44, "BS", "BHS", "Bahamas");
        public static EMVCountryCode BHR = new EMVCountryCode(48, "BH", "BHR", "Bahrain");
        public static EMVCountryCode BGD = new EMVCountryCode(50, "BD", "BGD", "Bangladesh");
        public static EMVCountryCode BRB = new EMVCountryCode(52, "BB", "BRB", "Barbados");
        public static EMVCountryCode BLR = new EMVCountryCode(112, "BY", "BLR", "Belarus");
        public static EMVCountryCode BEL = new EMVCountryCode(56, "BE", "BEL", "Belgium");
        public static EMVCountryCode BLZ = new EMVCountryCode(84, "BZ", "BLZ", "Belize");
        public static EMVCountryCode BEN = new EMVCountryCode(204, "BJ", "BEN", "Benin");
        public static EMVCountryCode BMU = new EMVCountryCode(60, "BM", "BMU", "Bermuda");
        public static EMVCountryCode BTN = new EMVCountryCode(64, "BT", "BTN", "Bhutan");
        public static EMVCountryCode BOL = new EMVCountryCode(68, "BO", "BOL", "Bolivia, Plurinational State of");
        public static EMVCountryCode BES = new EMVCountryCode(535, "BQ", "BES", "Bonaire, Sint Eustatius and Saba");
        public static EMVCountryCode BIH = new EMVCountryCode(70, "BA", "BIH", "Bosnia and Herzegovina");
        public static EMVCountryCode BWA = new EMVCountryCode(72, "BW", "BWA", "Botswana");
        public static EMVCountryCode BVT = new EMVCountryCode(74, "BV", "BVT", "Bouvet Island");
        public static EMVCountryCode BRA = new EMVCountryCode(76, "BR", "BRA", "Brazil");
        public static EMVCountryCode IOT = new EMVCountryCode(86, "IO", "IOT", "British Indian Ocean Territory");
        public static EMVCountryCode BRN = new EMVCountryCode(96, "BN", "BRN", "Brunei Darussalam");
        public static EMVCountryCode BGR = new EMVCountryCode(100, "BG", "BGR", "Bulgaria");
        public static EMVCountryCode BFA = new EMVCountryCode(854, "BF", "BFA", "Burkina Faso");
        public static EMVCountryCode BDI = new EMVCountryCode(108, "BI", "BDI", "Burundi");
        public static EMVCountryCode KHM = new EMVCountryCode(116, "KH", "KHM", "Cambodia");
        public static EMVCountryCode CMR = new EMVCountryCode(120, "CM", "CMR", "Cameroon");
        public static EMVCountryCode CAN = new EMVCountryCode(124, "CA", "CAN", "Canada");
        public static EMVCountryCode CPV = new EMVCountryCode(132, "CV", "CPV", "Cape Verde");
        public static EMVCountryCode CYM = new EMVCountryCode(136, "KY", "CYM", "Cayman Islands");
        public static EMVCountryCode CAF = new EMVCountryCode(140, "CF", "CAF", "Central African Republic");
        public static EMVCountryCode TCD = new EMVCountryCode(148, "TD", "TCD", "Chad");
        public static EMVCountryCode CHL = new EMVCountryCode(152, "CL", "CHL", "Chile");
        public static EMVCountryCode CHN = new EMVCountryCode(156, "CN", "CHN", "China");
        public static EMVCountryCode CXR = new EMVCountryCode(162, "CX", "CXR", "Christmas Island");
        public static EMVCountryCode CCK = new EMVCountryCode(166, "CC", "CCK", "Cocos (Keeling) Islands");
        public static EMVCountryCode COL = new EMVCountryCode(170, "CO", "COL", "Colombia");
        public static EMVCountryCode COM = new EMVCountryCode(174, "KM", "COM", "Comoros");
        public static EMVCountryCode COG = new EMVCountryCode(178, "CG", "COG", "Congo");
        public static EMVCountryCode COD = new EMVCountryCode(180, "CD", "COD", "Congo, the Democratic Republic of the");
        public static EMVCountryCode COK = new EMVCountryCode(184, "CK", "COK", "Cook Islands");
        public static EMVCountryCode CRI = new EMVCountryCode(188, "CR", "CRI", "Costa Rica");
        public static EMVCountryCode CIV = new EMVCountryCode(384, "CI", "CIV", "Côte d'Ivoire");
        public static EMVCountryCode HRV = new EMVCountryCode(191, "HR", "HRV", "Croatia");
        public static EMVCountryCode CUB = new EMVCountryCode(192, "CU", "CUB", "Cuba");
        public static EMVCountryCode CUW = new EMVCountryCode(531, "CW", "CUW", "Curaçao");
        public static EMVCountryCode CYP = new EMVCountryCode(196, "CY", "CYP", "Cyprus");
        public static EMVCountryCode CZE = new EMVCountryCode(203, "CZ", "CZE", "Czech Republic");
        public static EMVCountryCode DNK = new EMVCountryCode(208, "DK", "DNK", "Denmark");
        public static EMVCountryCode DJI = new EMVCountryCode(262, "DJ", "DJI", "Djibouti");
        public static EMVCountryCode DMA = new EMVCountryCode(212, "DM", "DMA", "Dominica");
        public static EMVCountryCode DOM = new EMVCountryCode(214, "DO", "DOM", "Dominican Republic");
        public static EMVCountryCode ECU = new EMVCountryCode(218, "EC", "ECU", "Ecuador");
        public static EMVCountryCode EGY = new EMVCountryCode(818, "EG", "EGY", "Egypt");
        public static EMVCountryCode SLV = new EMVCountryCode(222, "SV", "SLV", "El Salvador");
        public static EMVCountryCode GNQ = new EMVCountryCode(226, "GQ", "GNQ", "Equatorial Guinea");
        public static EMVCountryCode ERI = new EMVCountryCode(232, "ER", "ERI", "Eritrea");
        public static EMVCountryCode EST = new EMVCountryCode(233, "EE", "EST", "Estonia");
        public static EMVCountryCode ETH = new EMVCountryCode(231, "ET", "ETH", "Ethiopia");
        public static EMVCountryCode FLK = new EMVCountryCode(238, "FK", "FLK", "Falkland Islands (Malvinas)");
        public static EMVCountryCode FRO = new EMVCountryCode(234, "FO", "FRO", "Faroe Islands");
        public static EMVCountryCode FJI = new EMVCountryCode(242, "FJ", "FJI", "Fiji");
        public static EMVCountryCode FIN = new EMVCountryCode(246, "FI", "FIN", "Finland");
        public static EMVCountryCode FRA = new EMVCountryCode(250, "FR", "FRA", "France");
        public static EMVCountryCode GUF = new EMVCountryCode(254, "GF", "GUF", "French Guiana");
        public static EMVCountryCode PYF = new EMVCountryCode(258, "PF", "PYF", "French Polynesia");
        public static EMVCountryCode ATF = new EMVCountryCode(260, "TF", "ATF", "French Southern Territories");
        public static EMVCountryCode GAB = new EMVCountryCode(266, "GA", "GAB", "Gabon");
        public static EMVCountryCode GMB = new EMVCountryCode(270, "GM", "GMB", "Gambia");
        public static EMVCountryCode GEO = new EMVCountryCode(268, "GE", "GEO", "Georgia");
        public static EMVCountryCode DEU = new EMVCountryCode(276, "DE", "DEU", "Germany");
        public static EMVCountryCode GHA = new EMVCountryCode(288, "GH", "GHA", "Ghana");
        public static EMVCountryCode GIB = new EMVCountryCode(292, "GI", "GIB", "Gibraltar");
        public static EMVCountryCode GRC = new EMVCountryCode(300, "GR", "GRC", "Greece");
        public static EMVCountryCode GRL = new EMVCountryCode(304, "GL", "GRL", "Greenland");
        public static EMVCountryCode GRD = new EMVCountryCode(308, "GD", "GRD", "Grenada");
        public static EMVCountryCode GLP = new EMVCountryCode(312, "GP", "GLP", "Guadeloupe");
        public static EMVCountryCode GUM = new EMVCountryCode(316, "GU", "GUM", "Guam");
        public static EMVCountryCode GTM = new EMVCountryCode(320, "GT", "GTM", "Guatemala");
        public static EMVCountryCode GGY = new EMVCountryCode(831, "GG", "GGY", "Guernsey");
        public static EMVCountryCode GIN = new EMVCountryCode(324, "GN", "GIN", "Guinea");
        public static EMVCountryCode GNB = new EMVCountryCode(624, "GW", "GNB", "Guinea-Bissau");
        public static EMVCountryCode GUY = new EMVCountryCode(328, "GY", "GUY", "Guyana");
        public static EMVCountryCode HTI = new EMVCountryCode(332, "HT", "HTI", "Haiti");
        public static EMVCountryCode HMD = new EMVCountryCode(334, "HM", "HMD", "Heard Island and McDonald Islands");
        public static EMVCountryCode VAT = new EMVCountryCode(336, "VA", "VAT", "Holy See (Vatican City State)");
        public static EMVCountryCode HND = new EMVCountryCode(340, "HN", "HND", "Honduras");
        public static EMVCountryCode HKG = new EMVCountryCode(344, "HK", "HKG", "Hong Kong");
        public static EMVCountryCode HUN = new EMVCountryCode(348, "HU", "HUN", "Hungary");
        public static EMVCountryCode ISL = new EMVCountryCode(352, "IS", "ISL", "Iceland");
        public static EMVCountryCode IND = new EMVCountryCode(356, "IN", "IND", "India");
        public static EMVCountryCode IDN = new EMVCountryCode(360, "ID", "IDN", "Indonesia");
        public static EMVCountryCode IRN = new EMVCountryCode(364, "IR", "IRN", "Iran, Islamic Republic of");
        public static EMVCountryCode IRQ = new EMVCountryCode(368, "IQ", "IRQ", "Iraq");
        public static EMVCountryCode IRL = new EMVCountryCode(372, "IE", "IRL", "Ireland");
        public static EMVCountryCode IMN = new EMVCountryCode(833, "IM", "IMN", "Isle of Man");
        public static EMVCountryCode ISR = new EMVCountryCode(376, "IL", "ISR", "Israel");
        public static EMVCountryCode ITA = new EMVCountryCode(380, "IT", "ITA", "Italy");
        public static EMVCountryCode JAM = new EMVCountryCode(388, "JM", "JAM", "Jamaica");
        public static EMVCountryCode JPN = new EMVCountryCode(392, "JP", "JPN", "Japan");
        public static EMVCountryCode JEY = new EMVCountryCode(832, "JE", "JEY", "Jersey");
        public static EMVCountryCode JOR = new EMVCountryCode(400, "JO", "JOR", "Jordan");
        public static EMVCountryCode KAZ = new EMVCountryCode(398, "KZ", "KAZ", "Kazakhstan");
        public static EMVCountryCode KEN = new EMVCountryCode(404, "KE", "KEN", "Kenya");
        public static EMVCountryCode KIR = new EMVCountryCode(296, "KI", "KIR", "Kiribati");
        public static EMVCountryCode PRK = new EMVCountryCode(408, "KP", "PRK", "Korea, Democratic People's Republic of");
        public static EMVCountryCode KOR = new EMVCountryCode(410, "KR", "KOR", "Korea, Republic of");
        public static EMVCountryCode KWT = new EMVCountryCode(414, "KW", "KWT", "Kuwait");
        public static EMVCountryCode KGZ = new EMVCountryCode(417, "KG", "KGZ", "Kyrgyzstan");
        public static EMVCountryCode LAO = new EMVCountryCode(418, "LA", "LAO", "Lao People's Democratic Republic");
        public static EMVCountryCode LVA = new EMVCountryCode(428, "LV", "LVA", "Latvia");
        public static EMVCountryCode LBN = new EMVCountryCode(422, "LB", "LBN", "Lebanon");
        public static EMVCountryCode LSO = new EMVCountryCode(426, "LS", "LSO", "Lesotho");
        public static EMVCountryCode LBR = new EMVCountryCode(430, "LR", "LBR", "Liberia");
        public static EMVCountryCode LBY = new EMVCountryCode(434, "LY", "LBY", "Libya");
        public static EMVCountryCode LIE = new EMVCountryCode(438, "LI", "LIE", "Liechtenstein");
        public static EMVCountryCode LTU = new EMVCountryCode(440, "LT", "LTU", "Lithuania");
        public static EMVCountryCode LUX = new EMVCountryCode(442, "LU", "LUX", "Luxembourg");
        public static EMVCountryCode MAC = new EMVCountryCode(446, "MO", "MAC", "Macao");
        public static EMVCountryCode MKD = new EMVCountryCode(807, "MK", "MKD", "Macedonia, the former Yugoslav Republic of");
        public static EMVCountryCode MDG = new EMVCountryCode(450, "MG", "MDG", "Madagascar");
        public static EMVCountryCode MWI = new EMVCountryCode(454, "MW", "MWI", "Malawi");
        public static EMVCountryCode MYS = new EMVCountryCode(458, "MY", "MYS", "Malaysia");
        public static EMVCountryCode MDV = new EMVCountryCode(462, "MV", "MDV", "Maldives");
        public static EMVCountryCode MLI = new EMVCountryCode(466, "ML", "MLI", "Mali");
        public static EMVCountryCode MLT = new EMVCountryCode(470, "MT", "MLT", "Malta");
        public static EMVCountryCode MHL = new EMVCountryCode(584, "MH", "MHL", "Marshall Islands");
        public static EMVCountryCode MTQ = new EMVCountryCode(474, "MQ", "MTQ", "Martinique");
        public static EMVCountryCode MRT = new EMVCountryCode(478, "MR", "MRT", "Mauritania");
        public static EMVCountryCode MUS = new EMVCountryCode(480, "MU", "MUS", "Mauritius");
        public static EMVCountryCode MYT = new EMVCountryCode(175, "YT", "MYT", "Mayotte");
        public static EMVCountryCode MEX = new EMVCountryCode(484, "MX", "MEX", "Mexico");
        public static EMVCountryCode FSM = new EMVCountryCode(583, "FM", "FSM", "Micronesia, Federated States of");
        public static EMVCountryCode MDA = new EMVCountryCode(498, "MD", "MDA", "Moldova, Republic of");
        public static EMVCountryCode MCO = new EMVCountryCode(492, "MC", "MCO", "Monaco");
        public static EMVCountryCode MNG = new EMVCountryCode(496, "MN", "MNG", "Mongolia");
        public static EMVCountryCode MNE = new EMVCountryCode(499, "ME", "MNE", "Montenegro");
        public static EMVCountryCode MSR = new EMVCountryCode(500, "MS", "MSR", "Montserrat");
        public static EMVCountryCode MAR = new EMVCountryCode(504, "MA", "MAR", "Morocco");
        public static EMVCountryCode MOZ = new EMVCountryCode(508, "MZ", "MOZ", "Mozambique");
        public static EMVCountryCode MMR = new EMVCountryCode(104, "MM", "MMR", "Myanmar");
        public static EMVCountryCode NAM = new EMVCountryCode(516, "NA", "NAM", "Namibia");
        public static EMVCountryCode NRU = new EMVCountryCode(520, "NR", "NRU", "Nauru");
        public static EMVCountryCode NPL = new EMVCountryCode(524, "NP", "NPL", "Nepal");
        public static EMVCountryCode NLD = new EMVCountryCode(528, "NL", "NLD", "Netherlands");
        public static EMVCountryCode NCL = new EMVCountryCode(540, "NC", "NCL", "New Caledonia");
        public static EMVCountryCode NZL = new EMVCountryCode(554, "NZ", "NZL", "New Zealand");
        public static EMVCountryCode NIC = new EMVCountryCode(558, "NI", "NIC", "Nicaragua");
        public static EMVCountryCode NER = new EMVCountryCode(562, "NE", "NER", "Niger");
        public static EMVCountryCode NGA = new EMVCountryCode(566, "NG", "NGA", "Nigeria");
        public static EMVCountryCode NIU = new EMVCountryCode(570, "NU", "NIU", "Niue");
        public static EMVCountryCode NFK = new EMVCountryCode(574, "NF", "NFK", "Norfolk Island");
        public static EMVCountryCode MNP = new EMVCountryCode(580, "MP", "MNP", "Northern Mariana Islands");
        public static EMVCountryCode NOR = new EMVCountryCode(578, "NO", "NOR", "Norway");
        public static EMVCountryCode OMN = new EMVCountryCode(512, "OM", "OMN", "Oman");
        public static EMVCountryCode PAK = new EMVCountryCode(586, "PK", "PAK", "Pakistan");
        public static EMVCountryCode PLW = new EMVCountryCode(585, "PW", "PLW", "Palau");
        public static EMVCountryCode PSE = new EMVCountryCode(275, "PS", "PSE", "Palestine, State of");
        public static EMVCountryCode PAN = new EMVCountryCode(591, "PA", "PAN", "Panama");
        public static EMVCountryCode PNG = new EMVCountryCode(598, "PG", "PNG", "Papua New Guinea");
        public static EMVCountryCode PRY = new EMVCountryCode(600, "PY", "PRY", "Paraguay");
        public static EMVCountryCode PER = new EMVCountryCode(604, "PE", "PER", "Peru");
        public static EMVCountryCode PHL = new EMVCountryCode(608, "PH", "PHL", "Philippines");
        public static EMVCountryCode PCN = new EMVCountryCode(612, "PN", "PCN", "Pitcairn");
        public static EMVCountryCode POL = new EMVCountryCode(616, "PL", "POL", "Poland");
        public static EMVCountryCode PRT = new EMVCountryCode(620, "PT", "PRT", "Portugal");
        public static EMVCountryCode PRI = new EMVCountryCode(630, "PR", "PRI", "Puerto Rico");
        public static EMVCountryCode QAT = new EMVCountryCode(634, "QA", "QAT", "Qatar");
        public static EMVCountryCode REU = new EMVCountryCode(638, "RE", "REU", "Réunion");
        public static EMVCountryCode ROU = new EMVCountryCode(642, "RO", "ROU", "Romania");
        public static EMVCountryCode RUS = new EMVCountryCode(643, "RU", "RUS", "Russian Federation");
        public static EMVCountryCode RWA = new EMVCountryCode(646, "RW", "RWA", "Rwanda");
        public static EMVCountryCode BLM = new EMVCountryCode(652, "BL", "BLM", "Saint Barthélemy");
        public static EMVCountryCode SHN = new EMVCountryCode(654, "SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha");
        public static EMVCountryCode KNA = new EMVCountryCode(659, "KN", "KNA", "Saint Kitts and Nevis");
        public static EMVCountryCode LCA = new EMVCountryCode(662, "LC", "LCA", "Saint Lucia");
        public static EMVCountryCode MAF = new EMVCountryCode(663, "MF", "MAF", "Saint Martin (French part)");
        public static EMVCountryCode SPM = new EMVCountryCode(666, "PM", "SPM", "Saint Pierre and Miquelon");
        public static EMVCountryCode VCT = new EMVCountryCode(670, "VC", "VCT", "Saint Vincent and the Grenadines");
        public static EMVCountryCode WSM = new EMVCountryCode(882, "WS", "WSM", "Samoa");
        public static EMVCountryCode SMR = new EMVCountryCode(674, "SM", "SMR", "San Marino");
        public static EMVCountryCode STP = new EMVCountryCode(678, "ST", "STP", "Sao Tome and Principe");
        public static EMVCountryCode SAU = new EMVCountryCode(682, "SA", "SAU", "Saudi Arabia");
        public static EMVCountryCode SEN = new EMVCountryCode(686, "SN", "SEN", "Senegal");
        public static EMVCountryCode SRB = new EMVCountryCode(688, "RS", "SRB", "Serbia");
        public static EMVCountryCode SYC = new EMVCountryCode(690, "SC", "SYC", "Seychelles");
        public static EMVCountryCode SLE = new EMVCountryCode(694, "SL", "SLE", "Sierra Leone");
        public static EMVCountryCode SGP = new EMVCountryCode(702, "SG", "SGP", "Singapore");
        public static EMVCountryCode SXM = new EMVCountryCode(534, "SX", "SXM", "Sint Maarten (Dutch part)");
        public static EMVCountryCode SVK = new EMVCountryCode(703, "SK", "SVK", "Slovakia");
        public static EMVCountryCode SVN = new EMVCountryCode(705, "SI", "SVN", "Slovenia");
        public static EMVCountryCode SLB = new EMVCountryCode(90, "SB", "SLB", "Solomon Islands");
        public static EMVCountryCode SOM = new EMVCountryCode(706, "SO", "SOM", "Somalia");
        public static EMVCountryCode ZAF = new EMVCountryCode(710, "ZA", "ZAF", "South Africa");
        public static EMVCountryCode SGS = new EMVCountryCode(239, "GS", "SGS", "South Georgia and the South Sandwich Islands");
        public static EMVCountryCode SSD = new EMVCountryCode(728, "SS", "SSD", "South Sudan");
        public static EMVCountryCode ESP = new EMVCountryCode(724, "ES", "ESP", "Spain");
        public static EMVCountryCode LKA = new EMVCountryCode(144, "LK", "LKA", "Sri Lanka");
        public static EMVCountryCode SDN = new EMVCountryCode(729, "SD", "SDN", "Sudan");
        public static EMVCountryCode SUR = new EMVCountryCode(740, "SR", "SUR", "Suriname");
        public static EMVCountryCode SJM = new EMVCountryCode(744, "SJ", "SJM", "Svalbard and Jan Mayen");
        public static EMVCountryCode SWZ = new EMVCountryCode(748, "SZ", "SWZ", "Swaziland");
        public static EMVCountryCode SWE = new EMVCountryCode(752, "SE", "SWE", "Sweden");
        public static EMVCountryCode CHE = new EMVCountryCode(756, "CH", "CHE", "Switzerland");
        public static EMVCountryCode SYR = new EMVCountryCode(760, "SY", "SYR", "Syrian Arab Republic");
        public static EMVCountryCode TWN = new EMVCountryCode(158, "TW", "TWN", "Taiwan, Province of China");
        public static EMVCountryCode TJK = new EMVCountryCode(762, "TJ", "TJK", "Tajikistan");
        public static EMVCountryCode TZA = new EMVCountryCode(834, "TZ", "TZA", "Tanzania, United Republic of");
        public static EMVCountryCode THA = new EMVCountryCode(764, "TH", "THA", "Thailand");
        public static EMVCountryCode TLS = new EMVCountryCode(626, "TL", "TLS", "Timor-Leste");
        public static EMVCountryCode TGO = new EMVCountryCode(768, "TG", "TGO", "Togo");
        public static EMVCountryCode TKL = new EMVCountryCode(772, "TK", "TKL", "Tokelau");
        public static EMVCountryCode TON = new EMVCountryCode(776, "TO", "TON", "Tonga");
        public static EMVCountryCode TTO = new EMVCountryCode(780, "TT", "TTO", "Trinidad and Tobago");
        public static EMVCountryCode TUN = new EMVCountryCode(788, "TN", "TUN", "Tunisia");
        public static EMVCountryCode TUR = new EMVCountryCode(792, "TR", "TUR", "Turkey");
        public static EMVCountryCode TKM = new EMVCountryCode(795, "TM", "TKM", "Turkmenistan");
        public static EMVCountryCode TCA = new EMVCountryCode(796, "TC", "TCA", "Turks and Caicos Islands");
        public static EMVCountryCode TUV = new EMVCountryCode(798, "TV", "TUV", "Tuvalu");
        public static EMVCountryCode UGA = new EMVCountryCode(800, "UG", "UGA", "Uganda");
        public static EMVCountryCode UKR = new EMVCountryCode(804, "UA", "UKR", "Ukraine");
        public static EMVCountryCode ARE = new EMVCountryCode(784, "AE", "ARE", "United Arab Emirates");
        public static EMVCountryCode GBR = new EMVCountryCode(826, "GB", "GBR", "United Kingdom");
        public static EMVCountryCode USA = new EMVCountryCode(840, "US", "USA", "United States");
        public static EMVCountryCode UMI = new EMVCountryCode(581, "UM", "UMI", "United States Minor Outlying Islands");
        public static EMVCountryCode URY = new EMVCountryCode(858, "UY", "URY", "Uruguay");
        public static EMVCountryCode UZB = new EMVCountryCode(860, "UZ", "UZB", "Uzbekistan");
        public static EMVCountryCode VUT = new EMVCountryCode(548, "VU", "VUT", "Vanuatu");
        public static EMVCountryCode VEN = new EMVCountryCode(862, "VE", "VEN", "Venezuela, Bolivarian Republic of");
        public static EMVCountryCode VNM = new EMVCountryCode(704, "VN", "VNM", "Viet Nam");
        public static EMVCountryCode VGB = new EMVCountryCode(92, "VG", "VGB", "Virgin Islands, British");
        public static EMVCountryCode VIR = new EMVCountryCode(850, "VI", "VIR", "Virgin Islands, U.S.");
        public static EMVCountryCode WLF = new EMVCountryCode(876, "WF", "WLF", "Wallis and Futuna");
        public static EMVCountryCode ESH = new EMVCountryCode(732, "EH", "ESH", "Western Sahara");
        public static EMVCountryCode YEM = new EMVCountryCode(887, "YE", "YEM", "Yemen");
        public static EMVCountryCode ZMB = new EMVCountryCode(894, "ZM", "ZMB", "Zambia");
        public static EMVCountryCode ZWE = new EMVCountryCode(716, "ZW", "ZWE", "Zimbabwe");

        static ISOCountryCodesEnum()
        {

            EnumList.Add(AFG);
            EnumList.Add(ALA);
            EnumList.Add(ALB);
            EnumList.Add(DZA);
            EnumList.Add(ASM);
            EnumList.Add(AND);
            EnumList.Add(AGO);
            EnumList.Add(AIA);
            EnumList.Add(ATA);
            EnumList.Add(ATG);
            EnumList.Add(ARG);
            EnumList.Add(ARM);
            EnumList.Add(ABW);
            EnumList.Add(AUS);
            EnumList.Add(AUT);
            EnumList.Add(AZE);
            EnumList.Add(BHS);
            EnumList.Add(BHR);
            EnumList.Add(BGD);
            EnumList.Add(BRB);
            EnumList.Add(BLR);
            EnumList.Add(BEL);
            EnumList.Add(BLZ);
            EnumList.Add(BEN);
            EnumList.Add(BMU);
            EnumList.Add(BTN);
            EnumList.Add(BOL);
            EnumList.Add(BES);
            EnumList.Add(BIH);
            EnumList.Add(BWA);
            EnumList.Add(BVT);
            EnumList.Add(BRA);
            EnumList.Add(IOT);
            EnumList.Add(BRN);
            EnumList.Add(BGR);
            EnumList.Add(BFA);
            EnumList.Add(BDI);
            EnumList.Add(KHM);
            EnumList.Add(CMR);
            EnumList.Add(CAN);
            EnumList.Add(CPV);
            EnumList.Add(CYM);
            EnumList.Add(CAF);
            EnumList.Add(TCD);
            EnumList.Add(CHL);
            EnumList.Add(CHN);
            EnumList.Add(CXR);
            EnumList.Add(CCK);
            EnumList.Add(COL);
            EnumList.Add(COM);
            EnumList.Add(COG);
            EnumList.Add(COD);
            EnumList.Add(COK);
            EnumList.Add(CRI);
            EnumList.Add(CIV);
            EnumList.Add(HRV);
            EnumList.Add(CUB);
            EnumList.Add(CUW);
            EnumList.Add(CYP);
            EnumList.Add(CZE);
            EnumList.Add(DNK);
            EnumList.Add(DJI);
            EnumList.Add(DMA);
            EnumList.Add(DOM);
            EnumList.Add(ECU);
            EnumList.Add(EGY);
            EnumList.Add(SLV);
            EnumList.Add(GNQ);
            EnumList.Add(ERI);
            EnumList.Add(EST);
            EnumList.Add(ETH);
            EnumList.Add(FLK);
            EnumList.Add(FRO);
            EnumList.Add(FJI);
            EnumList.Add(FIN);
            EnumList.Add(FRA);
            EnumList.Add(GUF);
            EnumList.Add(PYF);
            EnumList.Add(ATF);
            EnumList.Add(GAB);
            EnumList.Add(GMB);
            EnumList.Add(GEO);
            EnumList.Add(DEU);
            EnumList.Add(GHA);
            EnumList.Add(GIB);
            EnumList.Add(GRC);
            EnumList.Add(GRL);
            EnumList.Add(GRD);
            EnumList.Add(GLP);
            EnumList.Add(GUM);
            EnumList.Add(GTM);
            EnumList.Add(GGY);
            EnumList.Add(GIN);
            EnumList.Add(GNB);
            EnumList.Add(GUY);
            EnumList.Add(HTI);
            EnumList.Add(HMD);
            EnumList.Add(VAT);
            EnumList.Add(HND);
            EnumList.Add(HKG);
            EnumList.Add(HUN);
            EnumList.Add(ISL);
            EnumList.Add(IND);
            EnumList.Add(IDN);
            EnumList.Add(IRN);
            EnumList.Add(IRQ);
            EnumList.Add(IRL);
            EnumList.Add(IMN);
            EnumList.Add(ISR);
            EnumList.Add(ITA);
            EnumList.Add(JAM);
            EnumList.Add(JPN);
            EnumList.Add(JEY);
            EnumList.Add(JOR);
            EnumList.Add(KAZ);
            EnumList.Add(KEN);
            EnumList.Add(KIR);
            EnumList.Add(PRK);
            EnumList.Add(KOR);
            EnumList.Add(KWT);
            EnumList.Add(KGZ);
            EnumList.Add(LAO);
            EnumList.Add(LVA);
            EnumList.Add(LBN);
            EnumList.Add(LSO);
            EnumList.Add(LBR);
            EnumList.Add(LBY);
            EnumList.Add(LIE);
            EnumList.Add(LTU);
            EnumList.Add(LUX);
            EnumList.Add(MAC);
            EnumList.Add(MKD);
            EnumList.Add(MDG);
            EnumList.Add(MWI);
            EnumList.Add(MYS);
            EnumList.Add(MDV);
            EnumList.Add(MLI);
            EnumList.Add(MLT);
            EnumList.Add(MHL);
            EnumList.Add(MTQ);
            EnumList.Add(MRT);
            EnumList.Add(MUS);
            EnumList.Add(MYT);
            EnumList.Add(MEX);
            EnumList.Add(FSM);
            EnumList.Add(MDA);
            EnumList.Add(MCO);
            EnumList.Add(MNG);
            EnumList.Add(MNE);
            EnumList.Add(MSR);
            EnumList.Add(MAR);
            EnumList.Add(MOZ);
            EnumList.Add(MMR);
            EnumList.Add(NAM);
            EnumList.Add(NRU);
            EnumList.Add(NPL);
            EnumList.Add(NLD);
            EnumList.Add(NCL);
            EnumList.Add(NZL);
            EnumList.Add(NIC);
            EnumList.Add(NER);
            EnumList.Add(NGA);
            EnumList.Add(NIU);
            EnumList.Add(NFK);
            EnumList.Add(MNP);
            EnumList.Add(NOR);
            EnumList.Add(OMN);
            EnumList.Add(PAK);
            EnumList.Add(PLW);
            EnumList.Add(PSE);
            EnumList.Add(PAN);
            EnumList.Add(PNG);
            EnumList.Add(PRY);
            EnumList.Add(PER);
            EnumList.Add(PHL);
            EnumList.Add(PCN);
            EnumList.Add(POL);
            EnumList.Add(PRT);
            EnumList.Add(PRI);
            EnumList.Add(QAT);
            EnumList.Add(REU);
            EnumList.Add(ROU);
            EnumList.Add(RUS);
            EnumList.Add(RWA);
            EnumList.Add(BLM);
            EnumList.Add(SHN);
            EnumList.Add(KNA);
            EnumList.Add(LCA);
            EnumList.Add(MAF);
            EnumList.Add(SPM);
            EnumList.Add(VCT);
            EnumList.Add(WSM);
            EnumList.Add(SMR);
            EnumList.Add(STP);
            EnumList.Add(SAU);
            EnumList.Add(SEN);
            EnumList.Add(SRB);
            EnumList.Add(SYC);
            EnumList.Add(SLE);
            EnumList.Add(SGP);
            EnumList.Add(SXM);
            EnumList.Add(SVK);
            EnumList.Add(SVN);
            EnumList.Add(SLB);
            EnumList.Add(SOM);
            EnumList.Add(ZAF);
            EnumList.Add(SGS);
            EnumList.Add(SSD);
            EnumList.Add(ESP);
            EnumList.Add(LKA);
            EnumList.Add(SDN);
            EnumList.Add(SUR);
            EnumList.Add(SJM);
            EnumList.Add(SWZ);
            EnumList.Add(SWE);
            EnumList.Add(CHE);
            EnumList.Add(SYR);
            EnumList.Add(TWN);
            EnumList.Add(TJK);
            EnumList.Add(TZA);
            EnumList.Add(THA);
            EnumList.Add(TLS);
            EnumList.Add(TGO);
            EnumList.Add(TKL);
            EnumList.Add(TON);
            EnumList.Add(TTO);
            EnumList.Add(TUN);
            EnumList.Add(TUR);
            EnumList.Add(TKM);
            EnumList.Add(TCA);
            EnumList.Add(TUV);
            EnumList.Add(UGA);
            EnumList.Add(UKR);
            EnumList.Add(ARE);
            EnumList.Add(GBR);
            EnumList.Add(USA);
            EnumList.Add(UMI);
            EnumList.Add(URY);
            EnumList.Add(UZB);
            EnumList.Add(VUT);
            EnumList.Add(VEN);
            EnumList.Add(VNM);
            EnumList.Add(VGB);
            EnumList.Add(VIR);
            EnumList.Add(WLF);
            EnumList.Add(ESH);
            EnumList.Add(YEM);
            EnumList.Add(ZMB);
            EnumList.Add(ZWE);

        }
    }

    public class EMVCountryCode : EnumBase
    {
        public string A2Code { get; }

        public string A3Code { get; }
        public string CountryName { get; }

        public EMVCountryCode(int code, string a2Code, string a3Code, string countryName)
        {
            this.Code = code;
            this.A2Code = a2Code;
            this.A3Code = a3Code;
            this.CountryName = countryName;
        }
    }
}
